import Head from "next/head";
import Image from "next/image";

import localFont from "@next/font/local";

// Font files can be colocated inside of `pages`
const myFont = localFont({ src: "../public/Glysa.otf" });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pryma Records</title>
        <meta name="description" content="Generated by Pryma Records" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        className={myFont.className}
        style={{
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
          height: "100%",
          color: "white",
          gap: 20,
          fontSize: 18,
          fontWeight: 400,
        }}
      >
        <Image src="/logo.png" alt="Pryma Logo" width={200} height={40} />
        Coming soon
      </div>
    </>
  );
}
